name: Pckg Skeleton CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '8.0', '8.1' ]
    steps:

      - uses: actions/checkout@v2

      - name: Restore Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --dev --prefer-dist --no-progress --no-suggest --optimize-autoloader --ignore-platform-reqs

      - name: Restore Yarn dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: js-${{ hashFiles('yarn.lock') }}

      - name: Install Yarn dependencies
        run: yarn install --production --silent --ignore-engines

      - name: Copy Codeception config
        run: cp codeception.sample.yml codeception.yml

      - name: Create temp app dir
        run: "[ ! -d ./app ] && mkdir app"

      - name: Run tests
        run: composer test
